# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
gems: [jekyll-paginate]
# Setup
title:               Matney Design Co.
tagline:             'Designer & Web Developer'
description:         'We Design and Build responsive websites. We also Design Logos, Invitations, Business Cards, and just about anything else you can think of! Made by <a href="https://twitter.com/stoppre" target="_blank">@stoppre</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Rich Matney
  url:               https://twitter.com/stoppre
  email:             richyentam@gmail.com

# Custom vars
version:             1.0.0
